# Config file for automatic testing at travis-ci.org
sudo: required

dist: xenial

language: python

python:
  - 3.5

services:
  - rabbitmq

addons:
  postgresql: "9.5"

cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TESTENV=py35-django110-mezzanine423

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install tox coveralls

script: tox -e $TESTENV

after_success:
  - coveralls

sudo: false