# Config file for automatic testing at travis-ci.org

language: python

services:
  - rabbitmq

addons:
  postgresql: "9.3"

cache:
  directories:
    - $HOME/.pip-cache/

env:
#  - TESTENV=py27-django15
#  - TESTENV=py27-django16
#  - TESTENV=py33-django15
#  - TESTENV=py33-django16
  - TESTENV=py34-django15
  - TESTENV=py34-django16


before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install tox coveralls

script: tox -r -e $TESTENV

after_success:
  - coveralls