# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO_VERSION=1.5.8 MEZZANINE_VERSION=3.1.4
  - DJANGO_VERSION=1.6.5 MEZZANINE_VERSION=3.1.4
  - DJANGO_VERSION=1.5.8 MEZZANINE_VERSION=3.1.5
  - DJANGO_VERSION=1.6.5 MEZZANINE_VERSION=3.1.5

#services:
#  - rabbitmq

cache:
  directories:
    - $HOME/.pip-cache/

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# command to install dependencies
install:
  - pip install Django==$DJANGO_VERSION mezzanine==$MEZZANINE_VERSION --download-cache $HOME/.pip-cache
  - if [[ $DJANGO_VERSION == '1.5.8' ]]; then pip install django-discover-runner --download-cache $HOME/.pip-cache; fi
  - pip install -q -r requirements/requirements_test.txt --download-cache $HOME/.pip-cache

#before_script:
#  - psql -c 'create database mezzanine-helpdesk;' -U postgres

# command to run tests using coverage
script:
  - coverage run --source helpdesk --omit=*/migrations/*,*/demo* $(which py.test) tests
  - make test-functional

# report coverage to coveralls.io
after_success: coveralls
